#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=12:00:00
#PBS -N dsi-studio-atk
#PBS -l vmem=8gb

set -e  

dwi=$(jq -r .dwi config.json)
bval=$(jq -r .bvals config.json)
bvec=$(jq -r .bvecs config.json)
# create symbolic link here
source=${dwi##*/}
ln -sf ${dwi} ${source}

target=$(jq -r .target config.json)

if [ ! -z "$target" ]; then target="--track_id=${target}"; fi
if [ ! -z "$bval" ]; then bval="--bval=${bval}"; fi
if [ ! -z "$bvec" ]; then bvec="--bvec=${bvec}"; fi

# prepare parameters
other=$(jq -r .other config.json)
if [[ ${other:0:1} != '-' ]]
then 
  echo "other parameter not used"
  other=""
fi

echo "call dsi_studio --action=atk --source=${source} --report=report.txt ${bval} ${bvec} ${target} ${other} "
time singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=atk --source=${source} --report=report.txt --flip_by=1 ${bval} ${bvec} ${target} ${other}
echo "dsi_studio processing completed"

report=$( cat report.txt )

# generate report
echo "{ \"meta\": {\"method\": \"${report}\"}, \"brainlife\": [ {\"type\": \"info\", \"msg\": \"${report}\"} ] }" > product.json

       
# move files
mkdir -p tts/tts
mv **/*.tt.gz tts/tts

if [ ! -f "$fib" ]
then
  mkdir -p fib
  mv *.fib.gz fib/fib.gz
  mv *.fib.gz.hcp1065.inv.mapping.gz fib/fib.gz.hcp1065.inv.mapping.gz
fi

mkdir -p stat/tractmeasures
mv **/*.txt stat/tractmeasures
