#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=12:00:00
#PBS -N dsi-studio-atk
#PBS -l vmem=8gb

set -e  

dwi=$(jq -r .dwi config.json)
bval=$(jq -r .bvals config.json)
bvec=$(jq -r .bvecs config.json)

# create symbolic link here
dwi_base_name=${dwi##*/}
rm -f ${dwi_base_name}
ln -s ${dwi} ${dwi_base_name}


time singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=atk --source=${dwi_base_name} --bval=${bval} --bvec=${bvec}

# move files
mkdir tts
mv *tt.gz tts
cd tts
mkdir tts
mv *tt.gz tts
cd.. 

mkdir fib
mv *fib.gz fib
mv *mapping.gz fib

mkdir stat
mv *.txt stat
