#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=1:00:00
#PBS -N dsi-studio-atk

set -e  

dwi=$(jq -r .dwi config.json)
bval=$(jq -r .bvals config.json)
bvec=$(jq -r .bvecs config.json)

echo "dwi=${dwi}"
echo "bval=${bvals}"
echo "bvec=${bvecs}"

time singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=atk --source=${dwi} --bval=${bval} --bvec=${bvec}
